console-error-message: "&c&l(!)&f This command can only be executed by a player."
no-perm-message: "&c&l(!)&f You do not have permission to do this."
world-error-message: "&c&l(!)&f The command provided cannot be executed in this world."
player-offline-message: "&c&l(!)&f Could not find the specified player."
argument-error: "&c&l(!)&f A valid amount of arguments must be provided! Usage: <usage>"

queueCommand:
  queue-doesnot-exist: "&c&l(!)&f The queue provided does not exist!"
  queue-already-exists: "&c&l(!)&f The queue provided already exists!"
  current-queue-error: "&c&l(!)&f You cannot join another queue when you are already in one!"
  queue-created: "&6&l(!)&f The queue &e<queue>&f has been created. Modify any of the queue's settings in queues.yml."
  queue-deleted: "&6&l(!)&f The queue &e<queue>&f has been deleted."
  joined-queue: "&6&l(!)&f <player>&f has joined the queue &6(&b<playercount>&6/&b<maxplayercount>&6)&e."
  left-queue: "&6&l(!)&f <player>&f has left the queue &6(&b<playercount>&6/&b<maxplayercount>&6)&e."
  player-left-queue: "&6&l(!)&f You have left the queue."
  game-running-error: "&c&l(!)&f The lobby could not be joined because there are no available servers."
  leave-error-message: "&c&l(!)&f This command cannot be executed because you are not in a queue."